<%@ Page Culture="ru-RU" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <center>
        <h1>
            Резка металла</h1>
    </center>
    <br />
    <div>
        <center>
            <table border="0" cellspacing="0" cellpadding="0" class="rezka">
                <tbody>
                    <tr>
                        <td>
                            <b>АРМАТУРА</b>
                        </td>
                        <td>
                            <b>КРУГДСВАДРАТ ШЕСТИГР.</b>
                        </td>
                        <td>
                            <b>ТРУБА</b>
                        </td>
                        <td>
                            <b>ТРУБА ПРОФ</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            8-4,10-4,6-3
                        </td>
                        <td>
                            8-3, 10-4
                        </td>
                        <td>
                            15-6
                        </td>
                        <td>
                            15x15-6
                        </td>
                    </tr>
                    <tr>
                        <td>
                            12-5
                        </td>
                        <td>
                            12-5
                        </td>
                        <td>
                            20-6
                        </td>
                        <td>
                            20x20-6
                        </td>
                    </tr>
                    <tr>
                        <td>
                            14,16-6
                        </td>
                        <td>
                            14-6
                        </td>
                        <td>
                            25-7
                        </td>
                        <td>
                            25x25-6
                        </td>
                    </tr>
                    <tr>
                        <td>
                            18-8
                        </td>
                        <td>
                            16-6
                        </td>
                        <td>
                            32-8
                        </td>
                        <td>
                            30x30-7
                        </td>
                    </tr>
                    <tr>
                        <td>
                            20-10
                        </td>
                        <td>
                            18-8
                        </td>
                        <td>
                            40-10
                        </td>
                        <td>
                            40x20-8
                        </td>
                    </tr>
                    <tr>
                        <td>
                            22-12
                        </td>
                        <td>
                            20-10
                        </td>
                        <td>
                            50-12
                        </td>
                        <td>
                            40x25-8
                        </td>
                    </tr>
                    <tr>
                        <td>
                            25-15
                        </td>
                        <td>
                            22-12
                        </td>
                        <td>
                            57-12
                        </td>
                        <td>
                            40x40-9
                        </td>
                    </tr>
                    <tr>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            25-15
                        </td>
                        <td>
                            76-15
                        </td>
                        <td>
                            50x25-9
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>ЛИСТ</b>
                        </td>
                        <td>
                            28-25
                        </td>
                        <td>
                            89-18
                        </td>
                        <td>
                            50x30-9
                        </td>
                    </tr>
                    <tr>
                        <td>
                            2-45
                        </td>
                        <td>
                            30-25
                        </td>
                        <td>
                            102-20
                        </td>
                        <td>
                            50x50-10
                        </td>
                    </tr>
                    <tr>
                        <td>
                            3-68
                        </td>
                        <td>
                            32-25
                        </td>
                        <td>
                            108-25
                        </td>
                        <td>
                            60x30-10
                        </td>
                    </tr>
                    <tr>
                        <td>
                            4-90
                        </td>
                        <td>
                            36-30
                        </td>
                        <td>
                            114-25
                        </td>
                        <td>
                            60x40-10
                        </td>
                    </tr>
                    <tr>
                        <td>
                            5-112
                        </td>
                        <td>
                            40-35
                        </td>
                        <td>
                            127-30
                        </td>
                        <td>
                            60x60-13
                        </td>
                    </tr>
                    <tr>
                        <td>
                            6-135
                        </td>
                        <td>
                            41-40
                        </td>
                        <td>
                            133-40
                        </td>
                        <td>
                            80x40-13
                        </td>
                    </tr>
                    <tr>
                        <td>
                            8-180
                        </td>
                        <td>
                            46-45
                        </td>
                        <td>
                            159-50
                        </td>
                        <td>
                            80x80-18
                        </td>
                    </tr>
                    <tr>
                        <td>
                            10-225
                        </td>
                        <td>
                            55-100
                        </td>
                        <td>
                            219-70
                        </td>
                        <td>
                            100x50-18
                        </td>
                    </tr>
                    <tr>
                        <td>
                            12-270
                        </td>
                        <td>
                            60-110
                        </td>
                        <td>
                            273-100
                        </td>
                        <td>
                            120x60-20
                        </td>
                    </tr>
                    <tr>
                        <td>
                            14-315
                        </td>
                        <td>
                            90-150
                        </td>
                        <td>
                            325-125
                        </td>
                        <td>
                            100x100-22
                        </td>
                    </tr>
                    <tr>
                        <td>
                            16-360
                        </td>
                        <td>
                            110-250
                        </td>
                        <td>
                            530-150
                        </td>
                        <td>
                            150x150-45
                        </td>
                    </tr>
                    <tr>
                        <td>
                            20-450
                        </td>
                        <td>
                            120-270
                        </td>
                        <td>
                            <b>УГОЛОК</b>
                        </td>
                        <td>
                            160x160-45
                        </td>
                    </tr>
                    <tr>
                        <td>
                            25-562
                        </td>
                        <td>
                            130-290
                        </td>
                        <td>
                            25-6
                        </td>
                        <td>
                            <b>БАЛКА</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            30-675
                        </td>
                        <td>
                            160-330
                        </td>
                        <td>
                            32-7
                        </td>
                        <td>
                            10-20
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>ШВЕЛЛЕР</b>
                        </td>
                        <td>
                            <b>ПОЛОСА</b>
                        </td>
                        <td>
                            40-8
                        </td>
                        <td>
                            12-20
                        </td>
                    </tr>
                    <tr>
                        <td>
                            6,5-15
                        </td>
                        <td>
                            25-3
                        </td>
                        <td>
                            45-10
                        </td>
                        <td>
                            14-25
                        </td>
                    </tr>
                    <tr>
                        <td>
                            8-15
                        </td>
                        <td>
                            30-3
                        </td>
                        <td>
                            50-12
                        </td>
                        <td>
                            16-25
                        </td>
                    </tr>
                    <tr>
                        <td>
                            10-20
                        </td>
                        <td>
                            40-4
                        </td>
                        <td>
                            63-15
                        </td>
                        <td>
                            18-25
                        </td>
                    </tr>
                    <tr>
                        <td>
                            12-20
                        </td>
                        <td>
                            50-4
                        </td>
                        <td>
                            70-15
                        </td>
                        <td>
                            20-30
                        </td>
                    </tr>
                    <tr>
                        <td>
                            14-25
                        </td>
                        <td>
                            60-6
                        </td>
                        <td>
                            75-18
                        </td>
                        <td>
                            25-30
                        </td>
                    </tr>
                    <tr>
                        <td>
                            16-25
                        </td>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            90-16
                        </td>
                        <td>
                            30-40
                        </td>
                    </tr>
                    <tr>
                        <td>
                            18-25
                        </td>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            100-20
                        </td>
                        <td>
                            35-42
                        </td>
                    </tr>
                    <tr>
                        <td>
                            20-30
                        </td>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            125-25
                        </td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td>
                            22-35
                        </td>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            140-30
                        </td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td>
                            24-40
                        </td>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            160-40
                        </td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td>
                            27-45
                        </td>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            200-50
                        </td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td>
                            30-50
                        </td>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td>
                            40-55
                        </td>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                </tbody>
            </table>
        </center>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="LeftMenuContent" runat="server">
    <% Html.RenderPartial("ServiceMenu2"); %>
</asp:Content>
